### ISSUE TITLE
Web based IDE

### ISSUE THREAD

**Issue by rvion** [haskell/haskell-ide#8]
Now that `stack` and `stack-ide` are here, it should be fairly straightforward to create a web based ide.

I can think of 
 -  websocket proxy between web ui and stack-ide process
 - `ace9` for editor (see the kitchen sink demo and choose haskell https://ace.c9.io/build/kitchen-sink.html)
 - git integration for free via an open source tool like git-webui
 - `hoogle`, `HaRE`, `haddock`, `hlint`, `codex` all setup by stack directly and proxied by ide rest api
 - terminal for free with some open source tool like [shellinabox](https://code.google.com/p/shellinabox/) or whatever found on github (https://github.com/search?utf8=%E2%9C%93&q=web+terminal+)
 
We can also leverage docker for packaging and deploying components, or even offering users some quick scripts to package apps, etc.

What do you think ?

**Comment by alanz** [comment]
I think the idea behind haskell-ide is to be a daemon that supports multiple different frontends. A web interface would be just another one of these.

**Comment by rvion** [comment]
oh ok
